# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

tutorial: true

run:
  name: "romania-test"
  disable_progressbar: true
  shared_resources:
    policy: false

scenario:
  clusters:
  - 5
  opts:
  - ''

countries: ['RO']

snapshots:
  start: "2013-03-01"
  end: "2013-03-08"

electricity:
  co2limit_enable: true
  co2limit: 100.e+6

  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, OCGT, CCGT, nuclear]
    StorageUnit: [battery]
    Store: [H2]
    Link: [H2 pipeline]

  renewable_carriers: [solar, onwind, offwind-ac]
  estimate_renewable_capacities:
    enable: true
    from_gem: true
    year: 2020
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV: solar

atlite:
  default_cutout: europe-2013-sarah3-era5
  cutouts:
    europe-2013-sarah3-era5:
      module: [sarah, era5]
      x: [-12., 42.]
      y: [33., 72.]
      dx: 0.3
      dy: 0.3
      time: ['2013', '2013']

renewable:
  offwind-ac:
    max_depth: false
  offwind-dc:
    max_depth: false
  offwind-float:
    max_depth: false
    min_depth: false

clustering:
  exclude_carriers: ["OCGT", "offwind-ac", "coal"]
  temporal:
    resolution_elec: 24h

lines:
  dynamic_line_rating:
    activate: true
    max_line_rating: 1.3

solving:
  solver:
    name: highs
    options: highs-simplex

  check_objective:
    enable: false
